apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-165
spec:
  replicas: 0
  selector:
    matchLabels:
      app: test-app-165
  template:
    metadata:
      labels:
        app: test-app-165
    spec:
      containers:
        - name: app
          image: phamhoangkha1403/test-app-165-service:bf04b2de79c9699bd657b614ae1507598bee0f76@sha256:a7b3cba016444143ccaeed61d5c8ec690e470089f7f73d9fa1793cdda3461012
          ports:
            - containerPort: 0
